### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by benharvie** [JoeMrCoffee/OurNoteOrganizer#1]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@michaellok001) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

🟢 This report is most likely not a false positive, you can take the report seriously.

(cc @huntr-helper)

**Comment by JoeMrCoffee** [comment]
Thanks for reaching out. Excuse me if I'm a little cautious about this, could you please provide the just of the issue rather than asking for private contact methods? The site doesn't use Windows which seems to be much of what the researcher you point to works with, and honestly it's supposed to be deployed in an on prem environment, ideally not exposed to the greater Internet at large. Thank you again.

**Comment by JoeMrCoffee** [comment]
No description and no follow up after request for more info.
